name = "cfw-vue-ai"
compatibility_date = "2023-11-21"
node_compat = false
workers_dev = false
main = "./build/worker.mjs"
[site]
bucket = "../ui/build/client"
[dev]
port = 3000
[env.qa]
name = "cfw-vue-ai"
[env.qa.vars]
NODE_ENV = "development"
WORKER_ENVIRONMENT = "qa"
VITE_PORT = "3000"
VITE_LOG_LEVEL = "debug"
VITE_APP_NAME = "cfw-vue-ai"
VITE_API_VERSION = "0.0.1"
VITE_UI_VERSION = "0.0.1"
VITE_APP_URL = "http://localhost:3000"
VITE_API_URL = "http://localhost:3000"
NEXTAUTH_URL = "http://localhost:3000/api/auth"
LOG_LEVEL = "debug"
EMAIL_SERVER_HOST = "smtp.fastmail.com"
EMAIL_SERVER_PORT = "465"
EMAIL_SERVER_USER = "cfw-vue-ai-signups@shortpoet.com"
EMAIL_FROM = "cfw-vue-ai-signups@shortpoet.com"
SSR_BASE_PATHS = "about,api-data,auth,index"
