/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiViewer: typeof import('./components/base/ApiViewer.vue')['default']
    ApiViewerFetch: typeof import('./components/base/ApiViewerFetch.vue')['default']
    Counter: typeof import('./components/base/Counter.vue')['default']
    DropMenu: typeof import('./components/auth/DropMenu.vue')['default']
    Footer: typeof import('./components/base/Footer.vue')['default']
    JsonTree: typeof import('./components/base/JsonTree.vue')['default']
    Link: typeof import('./components/base/Link.vue')['default']
    Login: typeof import('./components/auth/Login.vue')['default']
    MainNav: typeof import('./components/base/MainNav.vue')['default']
    ProfileGithub: typeof import('./components/auth/ProfileGithub.vue')['default']
    TextInput: typeof import('./components/base/TextInput.vue')['default']
    TheCounter: typeof import('./components/base/TheCounter.vue')['default']
    TheInput: typeof import('./components/base/TheInput.vue')['default']
  }
}
